server:
  port: 8400
spring:
  application:
    name: springCloudZuulServer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  ignored-services: "*"
  routes:
    ribbon:
      path: /api/ribbon/**
      serviceId: springCloudRibbonClient
    feign:
      path: /api/feign/**
      serviceId: springCloudFeignClient
